[env:esp32-s3-banana-leaf]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
board = bpi_leaf_s3
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
lib_deps = 
	tttapa/Control Surface@^2.1.0
	bodmer/TFT_eSPI@^2.5.43

build_flags = 
	
	-ffast-math
	
	
	-D ARDUINO_USB_MODE=0
	-D CORE_DEBUG_LEVEL=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D USB_MANUFACTURER="\"TTGO\""
	-D USB_PRODUCT="\"TTGO\""
	
	-fsingle-precision-constant
	
	-I lib/esp-dsp/modules/fft/include
	-I lib/esp-dsp/modules/common/include
	-I lib/esp-dsp/modules/math/include
	-I lib/esp-dsp/modules/wind/include


	-D USER_SETUP_LOADED=1
    -include include/tft_setup.h

; Enable PSRAM
board_build.arduino.memory_type = qio_qspi
board_build.memory_type = qio_qspi

