[env:esp32-s3-banana-leaf]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Only Control Surface remains in lib_deps
lib_deps = 
	tttapa/Control Surface@^2.1.0

; Update flags to point to the new local lib location
build_flags = 
	-D ARDUINO_USB_MODE=0
	-D CORE_DEBUG_LEVEL=1
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-D TOUCH_CS=-1
	-I lib/esp-dsp/modules/fft/include
	-I lib/esp-dsp/modules/common/include
	-I lib/esp-dsp/modules/math/include
    -I lib/esp-dsp/modules/wind/include